name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run b

      - name: Test
        run: npm run ci

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
